server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/expense_splitter_final
    username: root
    password: Ganesh@18

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

jwt:
  secret: your_super_secret_key_1234567890
  expiration: 86400000